volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  # production_traefik: {}
  production_django_media: {}

networks: 
  mynet:
    external: true

services:
  django:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: project_production_django
    # container_name: project_production_django
    volumes:
      - production_django_media:/app/project/media
    depends_on:
      - postgres
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    labels:
      - "traefik.enable=true"           # This option overrides the provider value of exposedByDefault.
      - "traefik.http.routers.django.rule=Host(`my-home-build.com`)"
      - "traefik.http.services.django.loadbalancer.server.port=5000"
      - "traefik.http.routers.django.tls=true"
    networks:
      - mynet
    ports:
      - 5000:5000
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: project_production_postgres
    # container_name: project_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres
    networks:
      - mynet
