#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

# BUILD_ENV set from within relevant dockerfile
echo "start of $BUILD_ENV entrypoint"

set -e
echo "10"
# Run the webserver
exec /usr/local/bin/gunicorn config.wsgi --bind 0.0.0.0:5000 --chdir=/app
